FROM python:3
LABEL version = '1'
COPY requirements.txt /home/requirements.txt
RUN apt update && pip install -r /home/requirements.txt
COPY main.py /home/main.py  
COPY smoke_tests.py /home/smoke_tests.py
WORKDIR /home
ENTRYPOINT ["pytest", "-s", "smoke_tests.py"]
